FROM python:3.12.10-slim

WORKDIR /app

# -----------------------------------------
# requirements 설치
# LightGBM 빌드에 필요한 패키지 포함
# -----------------------------------------
COPY app/requirements.txt /app/requirements.txt

RUN apt-get update && apt-get install -y --no-install-recommends \
    && pip install --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt \
    && pip install --no-cache-dir debugpy 

# -----------------------------------------
# 애플리케이션 복사
# -----------------------------------------
COPY app /app

# -----------------------------------------
# VSCode Debug + Uvicorn 실행
# -----------------------------------------
CMD ["python", "-m", "debugpy", "--listen", "0.0.0.0:5678", "--wait-for-client", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
